import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, BatteryCharging, Box, ChevronDown, Cog, Download, Factory, Filter, Gauge, Hammer, Menu, MessageCircle, MoveRight, Search, ShieldCheck, Sparkles, Sun, Trash2, Truck, Wrench, X, Zap} from 'lucide-react';
import './styles.css';

const projects=[
 {id:'solar-car',name:'Solar Car',category:'Solar Projects',type:'Prototype',tech:'Solar',difficulty:'Advanced',desc:'A student-focused solar electric vehicle concept developed around a practical chassis, energy system and safety-focused build.',featured:true,icon:'sun'},
 {id:'waste',name:'Automatic Waste Segregation Machine',category:'Waste Management',type:'Major Project',tech:'Automation',difficulty:'Advanced',desc:'A practical machine concept for separating dry and wet waste with mechanical handling and automation.',featured:true,icon:'trash'},
 {id:'oil',name:'Oil Cruncher',category:'Mechanical Machines',type:'Prototype',tech:'Mechanical',difficulty:'Intermediate',desc:'Compact mechanical extraction/crushing equipment concept for student fabrication and experimentation.',icon:'gear'},
 {id:'coconut',name:'Coconut Cutting Machine',category:'Agricultural Machines',type:'Major Project',tech:'Mechanical',difficulty:'Intermediate',desc:'A machine concept focused on controlled coconut cutting with a fabrication-ready mechanical workflow.',icon:'cog'},
 {id:'road-picker',name:'Automatic Road Waste Picker',category:'Waste Management',type:'Custom Project',tech:'Mechatronics',difficulty:'Advanced',desc:'A mobile collection concept designed to automate roadside waste picking and reduce manual effort.',icon:'truck'},
 {id:'stair-trolley',name:'Staircase Climbing Trolley',category:'Mechanical Major Projects',type:'Major Project',tech:'Mechanical',difficulty:'Advanced',desc:'A mechanism-driven trolley concept for moving loads across stairs.',icon:'box'},
 {id:'roller',name:'Manual Roller Bending Machine',category:'Mechanical Design',type:'Mini Project',tech:'Mechanical',difficulty:'Intermediate',desc:'Manual rolling and bending mechanism for practical workshop learning.',icon:'gear'},
 {id:'box',name:'Box Transport Mechanism',category:'Automation',type:'Mini Project',tech:'Mechanical',difficulty:'Beginner',desc:'A compact transport mechanism for studying motion transfer and handling.',icon:'box'},
 {id:'windmill',name:'Levitating Frictionless Vertical Windmill',category:'Power Generation',type:'Major Project',tech:'Mechanical',difficulty:'Advanced',desc:'A vertical wind-energy concept exploring low-friction rotational design.',icon:'zap'},
 {id:'rowing',name:'Power Generator Pulley Rowing Machine',category:'Power Generation',type:'Prototype',tech:'Mechanical',difficulty:'Intermediate',desc:'A human-powered mechanical energy generation concept.',icon:'zap'},
 {id:'hacksaw',name:'Pneumatic Operated Double Hacksaw',category:'Pneumatic Projects',type:'Major Project',tech:'Pneumatic',difficulty:'Advanced',desc:'A pneumatic reciprocating cutting concept for workshop applications.',icon:'hammer'},
 {id:'hammer',name:'Automatic Pneumatic Hammer Machine',category:'Pneumatic Projects',type:'Mini Project',tech:'Pneumatic',difficulty:'Intermediate',desc:'A compact pneumatic impact mechanism for demonstrating automation.',icon:'hammer'},
 {id:'paper-cutter',name:'Automatic Pneumatic Paper Cutting Machine',category:'Pneumatic Projects',type:'Mini Project',tech:'Pneumatic',difficulty:'Intermediate',desc:'A pneumatic cutting mechanism for controlled sheet processing.',icon:'wrench'},
 {id:'scissor-jack',name:'Pneumatic Scissor Lift Jack',category:'Pneumatic Projects',type:'Prototype',tech:'Pneumatic',difficulty:'Intermediate',desc:'A lift mechanism combining scissor geometry with pneumatic actuation.',icon:'gauge'},
 {id:'gearbox',name:'5 Speed Gearbox Mechanism',category:'Mechanical Design',type:'Major Project',tech:'Mechanical',difficulty:'Advanced',desc:'A mechanical transmission study focused on gear selection and power flow.',icon:'gear'},
 {id:'mesh',name:'Chain Link Wire Mesh Making Machine',category:'Manufacturing',type:'Major Project',tech:'Mechanical',difficulty:'Advanced',desc:'A machine concept for repeatable wire forming and mesh production.',icon:'factory'},
 {id:'mashing',name:'Motorized Spring Assist Mashing Machine',category:'Mechanical Machines',type:'Prototype',tech:'Mechanical',difficulty:'Intermediate',desc:'Motorized mechanism concept with spring assistance for repetitive processing.',icon:'cog'},
 {id:'shoes',name:'DIY Scissor Lift Shoes',category:'Mechanical Mini Projects',type:'Mini Project',tech:'Mechanical',difficulty:'Beginner',desc:'A compact scissor-linkage project for exploring mechanical movement.',icon:'wrench'},
];
const categories=['All','Mechanical Major Projects','Mechanical Mini Projects','Mechatronics','Pneumatic Projects','Power Generation','Mechanical Design','Solar Projects','Automation','Robotics','Manufacturing','Waste Management','Agricultural Machines'];
const technologies=['All','Solar','Pneumatic','Hydraulic','Mechanical','Mechatronics','Automation','Robotics','Electrical + Mechanical'];
const types=['All','Major Project','Mini Project','Prototype','Custom Project'];
const difficulties=['All','Beginner','Intermediate','Advanced'];

function App(){
 const [menu,setMenu]=useState(false),[search,setSearch]=useState(''),[cat,setCat]=useState('All'),[tech,setTech]=useState('All'),[type,setType]=useState('All'),[difficulty,setDifficulty]=useState('All'),[selected,setSelected]=useState(null),[form,setForm]=useState({name:'',college:'',course:'',phone:'',idea:'',type:'Major Project'}),[submitted,setSubmitted]=useState(false);
 const solarRef=useRef(null); const [solarProgress,setSolarProgress]=useState(0);
 useEffect(()=>{const fn=()=>{if(!solarRef.current)return;const r=solarRef.current.getBoundingClientRect();const p=Math.max(0,Math.min(1,(window.innerHeight*.72-r.top)/(r.height-window.innerHeight*.45)));setSolarProgress(p)};fn();window.addEventListener('scroll',fn,{passive:true});return()=>window.removeEventListener('scroll',fn)},[]);
 const filtered=useMemo(()=>projects.filter(p=>(cat==='All'||p.category===cat)&&(tech==='All'||p.tech===tech)&&(type==='All'||p.type===type)&&(difficulty==='All'||p.difficulty===difficulty)&&(!search||p.name.toLowerCase().includes(search.toLowerCase())||p.desc.toLowerCase().includes(search.toLowerCase()))),[cat,tech,type,difficulty,search]);
 const icon=(kind)=>({sun:<Sun/>,trash:<Trash2/>,gear:<Cog/>,cog:<Cog/>,truck:<Truck/>,box:<Box/>,zap:<Zap/>,hammer:<Hammer/>,wrench:<Wrench/>,gauge:<Gauge/>,factory:<Factory/>}[kind]||<Cog/>);
 const scrollTo=id=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenu(false)};
 return <div className="app">
  <header className="nav"><div className="brand" onClick={()=>scrollTo('home')}><div className="brandMark"><Cog size={21}/></div><span>MECH<span>FORGE</span></span></div><button className="mobileMenu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''}>{[['Projects','projects'],['Categories','library'],['How We Build','process'],['About Us','why'],['Build Your Idea','idea'],['Contact','contact']].map(([x,id])=><button key={id} onClick={()=>scrollTo(id)}>{x}</button>)}<button className="navCta" onClick={()=>scrollTo('idea')}>Start Your Project <ArrowRight size={16}/></button></nav></header>
  <main>
   <section id="home" className="hero"><div className="heroGrid"/><div className="heroCopy"><div className="eyebrow"><span className="pulse"/> ENGINEERING INNOVATION LAB</div><h1>TURN YOUR<br/><em>ENGINEERING IDEA</em><br/>INTO REALITY.</h1><p>From concept and 3D design to fabrication and a working prototype — we help mechanical engineering students build real machines.</p><div className="heroActions"><button className="primary" onClick={()=>scrollTo('projects')}>Explore Projects <ArrowRight/></button><button className="ghost" onClick={()=>scrollTo('idea')}>Build My Idea <Wrench/></button></div><div className="heroStats"><span><b>IDEA</b> <MoveRight/></span><span><b>DESIGN</b> <MoveRight/></span><span><b>BUILD</b> <MoveRight/></span><span><b>WORKING MACHINE</b></span></div></div><div className="heroVisual"><div className="blueprint"><span>MECH / 01</span><span>PROTOTYPE SYSTEM</span></div><div className="machine"><div className="machineTop"><Sun className="sunIcon"/><div className="panel p1"/><div className="panel p2"/><div className="panel p3"/></div><div className="machineBody"><div className="cockpit"/><div className="motor"><Cog/></div></div><div className="wheel w1"/><div className="wheel w2"/><div className="wheel w3"/><div className="wheel w4"/></div><div className="scanLine"/></div></section>
   <section className="ticker"><div>DESIGN <span>×</span> FABRICATE <span>×</span> AUTOMATE <span>×</span> TEST <span>×</span> BUILD <span>×</span> DESIGN <span>×</span> FABRICATE <span>×</span> AUTOMATE <span>×</span></div></section>
   <section ref={solarRef} className="solarBuild" id="solar"><div className="sectionIntro"><div><div className="eyebrow orange">SIGNATURE BUILD EXPERIENCE</div><h2>BUILD THE<br/><em>SOLAR CAR.</em></h2></div><p>Scroll through the engineering sequence. Every component has a job. Every layer moves the idea closer to a working machine.</p></div><div className="buildStage"><div className="buildMeta"><span>ASSEMBLY SEQUENCE</span><b>{String(Math.min(9,Math.floor(solarProgress*10)+1)).padStart(2,'0')} / 09</b></div><div className="carCanvas"><div className="ground"/><div className="carLayer chassis" style={{opacity:Math.min(1,solarProgress*5),transform:`translateY(${Math.max(0,(1-solarProgress*5))*24}px)`}}><div className="frameRail"/><div className="frameRail rear"/><div className="axle"/></div><div className="carLayer panels" style={{opacity:Math.max(0,Math.min(1,(solarProgress-.15)*5)),transform:`translateY(${Math.max(0,(.55-solarProgress))*35}px)`}}><div className="solarPanel sp1"/><div className="solarPanel sp2"/><div className="solarPanel sp3"/></div><div className="carLayer battery" style={{opacity:Math.max(0,Math.min(1,(solarProgress-.3)*6)),transform:`translateY(${Math.max(0,(.7-solarProgress))*40}px)`}}><div className="batteryBox"><BatteryCharging/></div></div><div className="carLayer motorLayer" style={{opacity:Math.max(0,Math.min(1,(solarProgress-.42)*6))}}><div className="motorBox"><Cog/></div><div className="driveLine"/></div><div className="carLayer wheels" style={{opacity:Math.max(0,Math.min(1,(solarProgress-.52)*6)),transform:`scale(${.86+Math.min(.14,Math.max(0,(solarProgress-.52)*1.8))})`}}><i/><i/><i/><i/></div><div className="carLayer safety" style={{opacity:Math.max(0,Math.min(1,(solarProgress-.64)*7))}}><div className="rollbar"/><div className="steering"/></div><div className="carLayer body" style={{opacity:Math.max(0,Math.min(1,(solarProgress-.76)*7)),transform:`translateY(${Math.max(0,(.9-solarProgress))*28}px)`}}><div className="bodyShell"><div className="windshield"/><div className="nose"/></div></div></div><div className="buildSteps">{['Chassis / Frame','Solar Panels','Battery Pack','Electric Motor','Wheels & Tyres','Steering + Safety','Final Body','WORKING SOLAR CAR'].map((s,i)=><div className={solarProgress>i/8?'active':''} key={s}><span>0{i+1}</span>{s}</div>)}</div></div><div className="buildBottom"><span>THIS IS HOW WE BUILD.</span><strong>Not just an idea.<br/>A machine that works.</strong><button className="primary" onClick={()=>scrollTo('idea')}>Build Your Project <ArrowRight/></button></div></section>
   <section id="projects" className="projects section"><div className="sectionIntro"><div><div className="eyebrow">OUR WORK</div><h2>WHAT WE <em>BUILD.</em></h2></div><p>Real-world mechanical thinking, translated into student-friendly prototypes, fabrication and working systems.</p></div><div className="featuredGrid">{projects.filter(p=>p.featured).map(p=><ProjectCard key={p.id} p={p} icon={icon} onOpen={setSelected}/>)}</div></section>
   <section id="library" className="library section"><div className="libraryHead"><div><div className="eyebrow">DISCOVER • DESIGN • BUILD</div><h2>MECHANICAL ENGINEERING<br/><em>PROJECT LIBRARY.</em></h2></div><div className="libraryCount"><b>{filtered.length}</b><span>projects in MVP library</span></div></div><div className="controls"><div className="search"><Search size={18}/><input placeholder="Search projects, mechanisms, machines..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filters"><Filter size={16}/><select value={cat} onChange={e=>setCat(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select><select value={tech} onChange={e=>setTech(e.target.value)}>{technologies.map(x=><option key={x}>{x}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}>{types.map(x=><option key={x}>{x}</option>)}</select><select value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{difficulties.map(x=><option key={x}>{x}</option>)}</select></div></div><div className="categoryRail">{categories.slice(0,9).map(x=><button className={cat===x?'selected':''} key={x} onClick={()=>setCat(x)}>{x}</button>)}</div><div className="projectGrid">{filtered.map(p=><ProjectCard key={p.id} p={p} icon={icon} onOpen={setSelected}/>)}{!filtered.length&&<div className="empty">No projects match those filters. Try another combination.</div>}</div></section>
   <section id="process" className="process section"><div className="sectionIntro"><div><div className="eyebrow orange">HOW WE BUILD</div><h2>IDEA TO<br/><em>WORKING MACHINE.</em></h2></div><p>We combine mechanical design thinking, fabrication know-how and student-friendly guidance into one practical workflow.</p></div><div className="processLine">{[['01','IDEA','Understand the concept and the problem it should solve.'],['02','DESIGN','Create mechanical concepts, layouts and 3D-ready designs.'],['03','ENGINEERING','Select mechanisms, components and build approach.'],['04','MANUFACTURING','Fabrication, machining, assembly and finishing.'],['05','WORKING PROTOTYPE','Test, refine and deliver a machine you can demonstrate.']].map(([n,t,d])=><div className="processItem" key={n}><div className="processNum">{n}</div><div className="processIcon"><Cog/></div><h3>{t}</h3><p>{d}</p></div>)}</div></section>
   <section id="why" className="why section"><div className="sectionIntro"><div><div className="eyebrow">WHY US</div><h2>ENGINEERING THAT<br/><em>LEAVES THE SCREEN.</em></h2></div><p>Students don't need another PDF full of theory. They need a path from a rough idea to something they can touch, test and present.</p></div><div className="whyGrid">{[['Practical Engineering',Wrench,'Learn by building real mechanisms.'],['Custom Design',Cog,'Your idea gets a build path, not a template.'],['3D CAD Support',Box,'Turn concepts into clear design intent.'],['Fabrication',Factory,'Bridge the gap between drawing and metal.'],['Prototype Development',Sparkles,'Iterate toward a working demonstration.'],['Project Documentation',Download,'Organize the engineering story around the build.'],['Student-Friendly Guidance',MessageCircle,'Get help without needing to know everything first.'],['Working Models',Zap,'The goal is simple: make it work.']].map(([t,I,d])=><div className="whyCard" key={t}><I/><h3>{t}</h3><p>{d}</p></div>)}</div></section>
   <section id="idea" className="idea section"><div className="ideaVisual"><div className="ideaRing r1"/><div className="ideaRing r2"/><Cog size={90}/><div className="ideaLabel l1">YOUR IDEA</div><div className="ideaLabel l2">OUR ENGINEERING</div><div className="ideaLabel l3">WORKING MACHINE</div></div><div className="ideaCopy"><div className="eyebrow orange">START SOMETHING REAL</div><h2>HAVE YOUR OWN<br/><em>ENGINEERING IDEA?</em></h2><p>Don't know how to design or manufacture it? Tell us what you're imagining and we'll help map it into a practical prototype.</p>{submitted?<div className="success"><ShieldCheck/> Project idea captured for this MVP demo. We'll use this flow as the foundation for the production enquiry form.</div>:<form onSubmit={e=>{e.preventDefault();setSubmitted(true)}}><div className="formGrid"><input required placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="College" value={form.college} onChange={e=>setForm({...form,college:e.target.value})}/><input placeholder="Course / Branch" value={form.course} onChange={e=>setForm({...form,course:e.target.value})}/><input required placeholder="Phone / WhatsApp" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Major Project</option><option>Mini Project</option><option>Prototype</option><option>Custom Project</option></select><textarea required rows="4" placeholder="Tell us your project idea..." value={form.idea} onChange={e=>setForm({...form,idea:e.target.value})}/><label className="upload"><Download size={17}/> Upload idea / reference <span>UI only in MVP</span><input type="file"/></label><button className="primary" type="submit">Submit Project Idea <ArrowRight/></button></form>}</div></section>
  </main><footer id="contact"><div className="footerTop"><div><div className="brand"><div className="brandMark"><Cog size={21}/></div><span>MECH<span>FORGE</span></span></div><p>Engineering ideas into practical designs, fabricated prototypes and working machines for students and innovators.</p></div><div><b>PROJECTS</b><button onClick={()=>scrollTo('library')}>Project Library</button><button onClick={()=>scrollTo('solar')}>Solar Car</button><button onClick={()=>scrollTo('process')}>How We Build</button></div><div><b>CONNECT</b><button onClick={()=>scrollTo('idea')}>Build Your Idea</button><button>WhatsApp</button><button>Social Media</button></div><div><b>FOR COLLEGES</b><button>Project Guidance</button><button>Prototype Development</button><button>Custom Engineering</button></div></div><div className="footerBottom"><span>© 2026 MechForge. Built around the idea → machine journey.</span><span>Original MVP • Static data • No paid APIs</span></div></footer>
  {selected&&<ProjectModal p={selected} icon={icon} onClose={()=>setSelected(null)} onBuild={()=>{setSelected(null);scrollTo('idea')}}/>}
 </div>
}
function ProjectCard({p,icon,onOpen}){return <article className="projectCard" onClick={()=>onOpen(p)}><div className="projectArt"><div className="artGrid"/><div className="artIcon">{icon(p.icon)}</div><span className="tag">{p.category}</span><span className="view">View Project <ArrowRight size={15}/></span></div><div className="projectInfo"><div><h3>{p.name}</h3><p>{p.desc}</p></div><div className="chips"><span>{p.type}</span><span>{p.difficulty}</span></div></div></article>}
function ProjectModal({p,icon,onClose,onBuild}){return <div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><button className="close" onClick={onClose}><X/></button><div className="modalArt"><div className="artGrid"/><div className="modalIcon">{icon(p.icon)}</div><span className="tag">{p.category}</span></div><div className="modalBody"><div className="eyebrow">PROJECT PROFILE</div><h2>{p.name}</h2><p>{p.desc}</p><div className="specGrid"><div><small>PROJECT TYPE</small><b>{p.type}</b></div><div><small>TECHNOLOGY</small><b>{p.tech}</b></div><div><small>DIFFICULTY</small><b>{p.difficulty}</b></div><div><small>BUILD STATUS</small><b>Concept / Demo</b></div></div><div className="detailSteps">{['Overview','Problem Statement','How It Works','Mechanical Design','Components Required','Manufacturing Process','Assembly Process','Safety','Documentation'].map(x=><span key={x}>{x}</span>)}</div><div className="demoNote"><Sparkles/> Detailed engineering specifications, CAD files, drawings, photographs and videos are added per project when production content is available. No unsupported technical claims are shown in this MVP.</div><button className="primary" onClick={onBuild}>Request This Project <ArrowRight/></button></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
